# Generated by Django 5.1.6 on 2025-06-23 10:06

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='kaexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название экзамена')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('exam_date', models.DateTimeField(verbose_name='Дата проведения экзамена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam_images/', verbose_name='Изображение задания')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
            },
        ),
    ]
