# Generated by Django 5.1.6 on 2025-02-22 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_restaurant_remove_masterclass_address_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshops.restaurant', verbose_name='Ресторан'),
        ),
    ]
