# Generated by Django 5.1.6 on 2025-05-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_alter_record_options_review_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Видимость'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Видимость'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Видимость'),
        ),
    ]
