# Generated by Django 5.1.6 on 2025-05-21 12:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_comment_is_visible_review_is_visible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterclass',
            old_name='cuisine_id',
            new_name='cuisine',
        ),
        migrations.RenameField(
            model_name='masterclass',
            old_name='raiting',
            new_name='rating',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'video')},
        ),
    ]
