# Generated by Django 5.1.6 on 2025-06-02 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0008_masterclasschef_alter_masterclass_chefs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='workshops_c_created_8b1543_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['video'], name='workshops_c_video_i_1b7586_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'video'], name='workshops_l_user_id_0c8a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['created_at'], name='workshops_v_created_62ccfe_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['duration'], name='workshops_v_duratio_219317_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['likes_count'], name='workshops_v_likes_c_b45820_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['comments_count'], name='workshops_v_comment_c805df_idx'),
        ),
    ]
