# Generated by Django 5.1.6 on 2025-06-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0010_record_email_record_phone_record_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
